(() => {
 const addCss=(key,href)=>{if(!document.querySelector(`link[data-${key}]`)){const x=document.createElement('link');x.rel='stylesheet';x.href=href;x.setAttribute(`data-${key}`,'true');document.head.appendChild(x)}};
 addCss('orbit-mode','orbit-mode.css');addCss('orbit-polish','orbit-polish.css');addCss('orbit-qa','qa-fixes.css');addCss('orbit-qa-r2','qa-r2.css');addCss('orbit-qa-final','qa-final.css');addCss('logo-integrity','logo-integrity.css?v=22');addCss('mobile-emergency','mobile-emergency-fix.css?v=22');addCss('symbol-integrity','symbol-integrity.css?v=22');addCss('orbit-primary','orbit-primary.css?v=22');
 document.title='Косматика 2026 — Орбита';
 const themes={orbit:{cls:'theme-orbit',color:'#f6f6f2'},noosphere:{cls:'theme-noosphere',color:'#050711'},institute:{cls:'theme-institute',color:'#f1ede3'}};
 document.querySelectorAll('.quick-search kbd').forEach(e=>e.remove());document.querySelectorAll('.review-tabs button').forEach((e,i)=>{const b=e.querySelector('b');if(b)b.textContent=String(i+1)});document.querySelectorAll('[data-theme="synthesis"] span').forEach(e=>e.textContent='Орбита 2');
 document.querySelectorAll('.feature-card').forEach(c=>{const h=c.querySelector('h3');if(h?.textContent.includes('Космоздрав')){const t=c.querySelector('.tag'),p=c.querySelector('p');if(t)t.textContent='Концептуальная иллюстрация';if(p)p.textContent='Образный визуал проекта; не документальная фотография.'}});const note=document.querySelector('.visual-note small');if(note)note.textContent='Мотивы официальной символики используются в интерфейсе, но не заменяют и не изменяют сам герб';
 const params=new URLSearchParams(location.search),requested=params.get('theme');if(requested==='synthesis'){location.replace('orbit2.html');return;}let theme=themes[requested]?requested:'orbit';
 const reviewInner=document.querySelector('.review-bar__inner');let modeSwitch=document.querySelector('.orbit-mode-switch');if(reviewInner&&!modeSwitch){modeSwitch=document.createElement('div');modeSwitch.className='orbit-mode-switch';modeSwitch.innerHTML='<button type="button" data-orbit-mode="light" aria-label="Светлый режим">Светлая</button><button type="button" data-orbit-mode="dark" aria-label="Тёмный режим">Тёмная</button>';reviewInner.insertBefore(modeSwitch,reviewInner.querySelector('.review-tabs'))}
 const menu=document.getElementById('mainNav');if(menu&&!menu.querySelector('.mobile-lab-controls')){const lab=document.createElement('div');lab.className='mobile-lab-controls';lab.innerHTML='<p class="mobile-lab-title">Оформление</p><div class="mobile-lab-row"><button type="button" data-orbit-mode="light">Светлая</button><button type="button" data-orbit-mode="dark">Тёмная</button></div><p class="mobile-lab-title">Архив вариантов</p><div class="mobile-lab-row archive"><a href="?theme=noosphere">Ноосфера</a><a href="?theme=institute">Институт</a><a href="orbit2.html">Орбита 2</a></div>';menu.appendChild(lab)}
 let orbitMode=params.get('mode')||localStorage.getItem('cosmatica-orbit-mode')||'light';if(!['light','dark'].includes(orbitMode))orbitMode='light';
 const applyMode=(m,u=true)=>{orbitMode=m==='dark'?'dark':'light';document.body.classList.toggle('orbit-mode-dark',theme==='orbit'&&orbitMode==='dark');document.querySelectorAll('[data-orbit-mode]').forEach(b=>{const a=b.dataset.orbitMode===orbitMode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});localStorage.setItem('cosmatica-orbit-mode',orbitMode);if(u&&theme==='orbit'){const x=new URL(location.href);x.searchParams.set('mode',orbitMode);history.replaceState({},'',x)}};
 const applyTheme=(n,u=true)=>{if(n==='synthesis'){location.href='orbit2.html';return;}theme=themes[n]?n:'orbit';document.body.classList.remove('theme-orbit','theme-noosphere','theme-institute','theme-synthesis','orbit-mode-dark');document.body.classList.add(themes[theme].cls);document.querySelectorAll('[data-theme]').forEach(b=>{const a=b.dataset.theme===theme;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});if(u){const x=new URL(location.href);x.searchParams.set('theme',theme);if(theme==='orbit')x.searchParams.set('mode',orbitMode);else x.searchParams.delete('mode');history.replaceState({},'',x)}applyMode(orbitMode,false)};
 applyTheme(theme,false);applyMode(orbitMode,false);document.querySelectorAll('[data-theme]').forEach(b=>b.addEventListener('click',()=>applyTheme(b.dataset.theme)));document.querySelectorAll('[data-orbit-mode]').forEach(b=>b.addEventListener('click',()=>applyMode(b.dataset.orbitMode)));
 const toggle=document.querySelector('.menu-toggle');if(menu&&toggle){toggle.addEventListener('click',()=>{const o=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(o));toggle.textContent=o?'Закрыть':'Меню'});menu.addEventListener('click',e=>{if(e.target.closest('a')&&!e.target.closest('.mobile-lab-controls')&&innerWidth<=760){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.textContent='Меню'}})}
 const progress=document.getElementById('scrollProgress'),update=()=>{const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=`${max>0?Math.min(100,scrollY/max*100):0}%`};addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();
})();