(() => {
  const addCss=(key,href)=>{if(!document.querySelector(`link[data-${key}]`)){const x=document.createElement('link');x.rel='stylesheet';x.href=href;x.setAttribute(`data-${key}`,'true');document.head.appendChild(x)}};
  addCss('orbit-mode','orbit-mode.css');addCss('orbit-polish','orbit-polish.css');addCss('orbit-qa','qa-fixes.css');addCss('orbit-qa-r2','qa-r2.css');addCss('orbit-qa-final','qa-final.css');addCss('logo-integrity','logo-integrity.css?v=19');addCss('mobile-emergency','mobile-emergency-fix.css?v=19');addCss('symbol-integrity','symbol-integrity.css?v=19');

  document.title='Косматика 2026 — Орбита';
  const setMeta=(s,v)=>{const e=document.querySelector(s);if(e)e.setAttribute('content',v)};
  setMeta('meta[name="description"]','Рекомендуемое визуальное направление портала Русского космического общества — «Орбита» со светлым и тёмным режимами.');
  setMeta('meta[property="og:title"]','Косматика 2026 — рекомендуемое направление «Орбита»');
  setMeta('meta[property="og:description"]','Светлый и тёмный режимы «Орбиты» и альтернативные визуальные направления одного макета портала РКО.');
  setMeta('meta[name="twitter:title"]','Косматика 2026 — Орбита');setMeta('meta[name="twitter:description"]','Рекомендуемое визуальное направление портала РКО со светлым и тёмным режимами.');
  const themes={orbit:{cls:'theme-orbit',label:'ОРБИТА · вариант 1',color:'#f6f6f2'},noosphere:{cls:'theme-noosphere',label:'НООСФЕРА · вариант 2',color:'#050711'},institute:{cls:'theme-institute',label:'КОСМИЧЕСКИЙ ИНСТИТУТ · вариант 3',color:'#f1ede3'}};
  document.querySelectorAll('[data-theme="orbit"]').forEach(e=>e.setAttribute('aria-label','Вариант 1 — Орбита, рекомендуемое направление'));document.querySelectorAll('[data-theme="noosphere"]').forEach(e=>e.setAttribute('aria-label','Вариант 2 — Ноосфера'));document.querySelectorAll('[data-theme="institute"]').forEach(e=>e.setAttribute('aria-label','Вариант 3 — Космический институт'));document.querySelectorAll('[data-theme="synthesis"] span').forEach(e=>e.textContent='Орбита 2');document.querySelectorAll('[data-theme="synthesis"]').forEach(e=>e.setAttribute('aria-label','Вариант 4 — Орбита 2, UX-эксперимент'));document.querySelectorAll('.review-tabs button').forEach((e,i)=>{const b=e.querySelector('b');if(b)b.textContent=String(i+1)});document.querySelectorAll('.quick-search kbd').forEach(e=>e.remove());
  document.querySelectorAll('.feature-card').forEach(c=>{const h=c.querySelector('h3');if(h?.textContent.includes('Космоздрав')){const t=c.querySelector('.tag'),p=c.querySelector('p');if(t)t.textContent='Концептуальная иллюстрация';if(p)p.textContent='Образный визуал проекта; не документальная фотография.';}});const note=document.querySelector('.visual-note small');if(note)note.textContent='Мотивы официальной символики используются в интерфейсе, но не заменяют и не изменяют сам герб';
  const params=new URLSearchParams(location.search),requested=params.get('theme');if(requested==='synthesis'){location.replace('orbit2.html');return;}let theme=requested||localStorage.getItem('cosmatica-theme');if(!themes[theme])theme='orbit';const reviewInner=document.querySelector('.review-bar__inner');let modeSwitch=document.querySelector('.orbit-mode-switch');if(reviewInner&&!modeSwitch){modeSwitch=document.createElement('div');modeSwitch.className='orbit-mode-switch';modeSwitch.setAttribute('aria-label','Режим оформления Орбиты');modeSwitch.innerHTML='<button type="button" data-orbit-mode="light" aria-label="Светлый режим">Светлая</button><button type="button" data-orbit-mode="dark" aria-label="Тёмный режим">Тёмная</button>';const tabs=reviewInner.querySelector('.review-tabs');reviewInner.insertBefore(modeSwitch,tabs||null);}let orbitMode=params.get('mode')||localStorage.getItem('cosmatica-orbit-mode')||'light';if(!['light','dark'].includes(orbitMode))orbitMode='light';
  const applyOrbitMode=(m,u=true)=>{orbitMode=m==='dark'?'dark':'light';document.body.classList.toggle('orbit-mode-dark',theme==='orbit'&&orbitMode==='dark');document.querySelectorAll('[data-orbit-mode]').forEach(b=>{const a=b.dataset.orbitMode===orbitMode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});if(theme==='orbit')document.querySelector('meta[name="theme-color"]')?.setAttribute('content',orbitMode==='dark'?'#070a20':'#f7f7f3');localStorage.setItem('cosmatica-orbit-mode',orbitMode);if(u&&theme==='orbit'){const x=new URL(location.href);x.searchParams.set('mode',orbitMode);history.replaceState({},'',x)}};
  const applyTheme=(n,u=true)=>{if(n==='synthesis'){location.href='orbit2.html';return;}theme=themes[n]?n:'orbit';const s=themes[theme];document.body.classList.remove('theme-orbit','theme-noosphere','theme-institute','theme-synthesis','orbit-mode-dark');document.body.classList.add(s.cls);const badge=document.getElementById('prototypeBadge');if(badge)badge.textContent=s.label;document.querySelectorAll('[data-theme]').forEach(b=>{const a=b.dataset.theme===theme;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});localStorage.setItem('cosmatica-theme',theme);if(u){const x=new URL(location.href);x.searchParams.set('theme',theme);if(theme==='orbit')x.searchParams.set('mode',orbitMode);else x.searchParams.delete('mode');history.replaceState({},'',x)}applyOrbitMode(orbitMode,false);if(theme!=='orbit')document.querySelector('meta[name="theme-color"]')?.setAttribute('content',s.color)};
  applyTheme(theme,false);applyOrbitMode(orbitMode,false);document.querySelectorAll('[data-theme]').forEach(b=>b.addEventListener('click',()=>applyTheme(b.dataset.theme)));document.querySelectorAll('[data-orbit-mode]').forEach(b=>b.addEventListener('click',()=>applyOrbitMode(b.dataset.orbitMode)));
  const menu=document.getElementById('mainNav'),toggle=document.querySelector('.menu-toggle');if(menu&&toggle){toggle.addEventListener('click',()=>{const o=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(o));toggle.textContent=o?'Закрыть':'Меню'});menu.addEventListener('click',e=>{if(e.target.closest('a')&&innerWidth<=760){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.textContent='Меню'}})}
  const palette=document.getElementById('commandPalette'),openPalette=()=>{if(!palette)return;palette.showModal();setTimeout(()=>palette.querySelector('input')?.focus(),20)};document.querySelectorAll('[data-open-palette]').forEach(b=>b.addEventListener('click',openPalette));document.querySelectorAll('[data-close-palette]').forEach(b=>b.addEventListener('click',()=>palette?.close()));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape'&&palette?.open)palette.close()});palette?.addEventListener('click',e=>{if(e.target===palette)palette.close()});
  const progress=document.getElementById('scrollProgress'),updateProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight,value=max>0?(scrollY/max)*100:0;if(progress)progress.style.width=`${Math.min(100,Math.max(0,value))}%`};addEventListener('scroll',updateProgress,{passive:true});addEventListener('resize',updateProgress);updateProgress();
})();