let catalog=[],book=null,pdf=null,current=1,scale=1.15,renderTask=null,pageTextCache=new Map(),searchIndex=null;const $=s=>document.querySelector(s);pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const READER_API=(window.RKO_READER_API||localStorage.getItem('rkoReaderApi')||'https://rko-reader-api.vercel.app');
const speech={active:false,paused:false,page:1,chunks:[],index:0,token:0,utterance:null,switchId:0,restartTimer:null};const stopWords=new Set('и в во на не что он она это как к с со из за по от для а но же мы вы они я его ее их у о об до при бы был была были быть или который которая которые где когда уже еще'.split(' '));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}function norm(s){return(s||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9 ]+/g,' ').replace(/\s+/g,' ').trim()}function words(s){return norm(s).split(' ').filter(x=>x.length>2&&!stopWords.has(x))}
function splitSpeech(text,max=850){const sentences=(text||'').replace(/\s+/g,' ').match(/[^.!?…]+[.!?…]+|[^.!?…]+$/g)||[];const out=[];let cur='';for(const s of sentences){if((cur+' '+s).length>max&&cur){out.push(cur.trim());cur=s}else cur+=' '+s}if(cur.trim())out.push(cur.trim());return out}
async function loadCurrentText(){if(!pdf)return'';if(pageTextCache.has(current))return pageTextCache.get(current);const p=await pdf.getPage(current),tc=await p.getTextContent();const text=tc.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim();pageTextCache.set(current,text);return text}
async function renderPage(n,{keepSpeech=true}={}){if(!pdf)return;current=Math.max(1,Math.min(pdf.numPages,Number(n)||1));$('#page').value=current;$('#listenPage').textContent=current;$('#textPage').textContent=current;$('#prev').disabled=current<=1;$('#next').disabled=current>=pdf.numPages;const p=await pdf.getPage(current),vp=p.getViewport({scale});const canvas=$('#pdfCanvas'),ctx=canvas.getContext('2d');canvas.width=Math.floor(vp.width);canvas.height=Math.floor(vp.height);if(renderTask)try{renderTask.cancel()}catch{}renderTask=p.render({canvasContext:ctx,viewport:vp});try{await renderTask.promise}catch(e){if(e?.name!=='RenderingCancelledException')console.warn(e)}renderTask=null;const text=await loadCurrentText();$('#pageText').textContent=text||'На этой странице нет текстового слоя. PDF можно читать визуально, но для озвучивания этой страницы потребуется OCR.';$('#speak').disabled=!text&&!speech.active;if(keepSpeech&&speech.active){startSpeechAtPage(current)}else if(speech.active&&speech.page!==current){stopSpeech()}history.replaceState(null,'',`?book=${book.id}&page=${current}`)}
function setVoiceState(){const st=$('#voiceStatus');if(speech.active)st.textContent=speech.paused?`Пауза · стр. ${speech.page}`:`Читаю стр. ${speech.page}`;else st.textContent='Готово';$('#speak').disabled=speech.active&&!speech.paused;$('#pause').disabled=!speech.active;$('#stop').disabled=!speech.active;$('#pause').textContent=speech.paused?'▶ Продолжить':'Ⅱ Пауза'}
function selectedVoice(){const name=$('#voice').value;return speechSynthesis.getVoices().find(v=>v.name===name)||speechSynthesis.getVoices().find(v=>/^ru/i.test(v.lang))||null}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function cancelUtterance(){speech.token++;if(speech.restartTimer){clearTimeout(speech.restartTimer);speech.restartTimer=null}try{if(speechSynthesis.paused)speechSynthesis.resume()}catch{}speechSynthesis.cancel();speech.utterance=null}
function stopSpeech(){speech.switchId++;cancelUtterance();speech.active=false;speech.paused=false;speech.chunks=[];speech.index=0;setVoiceState()}
async function startSpeechAtPage(page,{freshSwitch=true,delay=220}={}){const switchId=freshSwitch?++speech.switchId:speech.switchId;cancelUtterance();speech.page=page;speech.index=0;speech.active=true;speech.paused=false;speech.chunks=[];setVoiceState();await sleep(delay);if(switchId!==speech.switchId||!speech.active||speech.page!==page)return;try{speechSynthesis.cancel()}catch{}await sleep(80);if(switchId!==speech.switchId||!speech.active||speech.page!==page)return;const text=await getPageText(page);if(switchId!==speech.switchId||!speech.active||speech.page!==page)return;if(!text||!text.trim()){speech.active=false;speech.paused=false;speech.chunks=[];setVoiceState();$('#voiceStatus').textContent='На странице нет текстового слоя';toast('Эта страница не содержит распознаваемого текста');return}speech.chunks=splitSpeech(text);setVoiceState();speakChunk()}
function speakChunk(){if(!speech.active||speech.paused)return;if(speech.index>=speech.chunks.length){if($('#autoNext').checked&&speech.page<pdf.numPages){manualPage(speech.page+1);}else stopSpeech();return}const token=++speech.token,u=new SpeechSynthesisUtterance(speech.chunks[speech.index]);speech.utterance=u;u.lang='ru-RU';u.rate=Number($('#rate').value);const v=selectedVoice();if(v)u.voice=v;u.onend=()=>{if(token!==speech.token)return;speech.index++;speakChunk()};u.onerror=e=>{if(token===speech.token&&e.error!=='interrupted')stopSpeech()};speechSynthesis.speak(u);setVoiceState()}
async function getPageText(n){if(pageTextCache.has(n))return pageTextCache.get(n);const p=await pdf.getPage(n),tc=await p.getTextContent(),t=tc.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim();pageTextCache.set(n,t);return t}
async function manualPage(n){const target=Math.max(1,Math.min(pdf?.numPages||1,Number(n)||1)),was=speech.active;let switchId=null;if(was){switchId=++speech.switchId;cancelUtterance();speech.active=true;speech.paused=false;speech.page=target;speech.chunks=[];speech.index=0;setVoiceState();$('#voiceStatus').textContent=`Переключаюсь на стр. ${target}`}await renderPage(target,{keepSpeech:false});if(was&&switchId===speech.switchId)await startSpeechAtPage(target,{freshSwitch:false,delay:320})}
function populateVoices(){const sel=$('#voice'),cur=sel.value,vs=speechSynthesis.getVoices().filter(v=>/^ru/i.test(v.lang)||/russian/i.test(v.name));sel.innerHTML='<option value="">Автоматически</option>'+vs.map(v=>`<option value="${v.name.replace(/"/g,'&quot;')}">${v.name} · ${v.lang}</option>`).join('');if([...sel.options].some(o=>o.value===cur))sel.value=cur}speechSynthesis.onvoiceschanged=populateVoices;
async function buildSearchIndex(){if(searchIndex)return searchIndex;$('#answer').innerHTML='<p>Индексирую текст книги…</p>';searchIndex=[];for(let i=1;i<=pdf.numPages;i++){const text=await getPageText(i);searchIndex.push({page:i,text,norm:norm(text)});if(i%20===0)$('#answer').innerHTML=`<p>Индексирую… ${i} / ${pdf.numPages}</p>`}return searchIndex}
function score(item,qw){let s=0;for(const w of qw){const c=item.norm.split(w).length-1;s+=Math.min(c,7)*(w.length>6?3:2);if(item.norm.includes(w))s+=2}return s}function snippet(text,qw){const n=norm(text);let pos=-1;for(const w of qw){const p=n.indexOf(w);if(p>=0){pos=p;break}}if(pos<0)return text.slice(0,260);const start=Math.max(0,pos-80);return(start?'…':'')+text.slice(start,start+360)+'…'}
async function ask(q){const qw=[...new Set(words(q))];if(!qw.length)return;const idx=await buildSearchIndex();const hits=idx.map(x=>({...x,score:score(x,qw)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,6);if(!hits.length){$('#answer').innerHTML='<p>Подходящих фрагментов не найдено. Попробуйте сформулировать вопрос иначе.</p>';return}$('#answer').innerHTML=`<p>Найдено ${hits.length} наиболее релевантных страниц:</p>`+hits.map(x=>`<button class="source" data-page="${x.page}"><b>стр. ${x.page}</b> — ${snippet(x.text,qw).replace(/[<&]/g,m=>m==='<'?'&lt;':'&amp;')}</button>`).join('');document.querySelectorAll('.source').forEach(b=>b.onclick=()=>{manualPage(Number(b.dataset.page));document.querySelector('[data-tab="text"]').click()})}
async function boot(){catalog=await fetch('../library/data/books.json').then(r=>r.json());const p=new URLSearchParams(location.search),id=Number(p.get('book'))||catalog[0]?.id;book=catalog.find(x=>x.id===id);if(!book)throw new Error('Книга не найдена');$('#title').textContent=book.title;$('#meta').textContent=[book.author,book.year,book.pages?book.pages+' стр.':'',book.format].filter(Boolean).join(' · ');$('#sourceLink').href=book.rko_url||'https://cosmatica.org/library';$('#driveOpen').href=book.drive_preview;const isPdf=(book.format||'').toUpperCase()==='PDF';if(!isPdf){$('#status').textContent='Формат '+book.format+' · Google Drive';$('#fallback').hidden=false;$('#pdfCanvas').hidden=true;return}$('#status').textContent='PDF.js · Google Drive · публичный доступ';if(!READER_API)throw new Error('Reader API ещё не подключён. Откройте файл на Google Drive или подключите Vercel API.');const pdfUrl=`${READER_API}/api/pdf?id=${encodeURIComponent(book.drive_id)}`;pdf=await pdfjsLib.getDocument({url:pdfUrl}).promise;$('#pages').textContent=pdf.numPages;$('#page').max=pdf.numPages;populateVoices();await renderPage(Math.min(Number(p.get('page'))||1,pdf.numPages),{keepSpeech:false})}
$('#prev').onclick=()=>manualPage(current-1);$('#next').onclick=()=>manualPage(current+1);$('#page').onchange=e=>manualPage(e.target.value);$('#zoomIn').onclick=()=>{scale=Math.min(2.5,scale+.15);renderPage(current,{keepSpeech:false})};$('#zoomOut').onclick=()=>{scale=Math.max(.55,scale-.15);renderPage(current,{keepSpeech:false})};setInterval(()=>{$('#zoomLabel').textContent=Math.round(scale*100)+'%'},300);
$('#speak').onclick=()=>{if(speech.active&&speech.paused){speech.paused=false;speechSynthesis.resume();setVoiceState()}else startSpeechAtPage(current)};$('#pause').onclick=()=>{if(!speech.active)return;if(speech.paused){speech.paused=false;speechSynthesis.resume()}else{speech.paused=true;speechSynthesis.pause()}setVoiceState()};$('#stop').onclick=stopSpeech;$('#rate').onchange=()=>{if(speech.active)startSpeechAtPage(speech.page)};$('#voice').onchange=()=>{if(speech.active)startSpeechAtPage(speech.page)};$('#copyText').onclick=async()=>{await navigator.clipboard.writeText($('#pageText').textContent);toast('Текст страницы скопирован')};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#askForm').onsubmit=e=>{e.preventDefault();ask($('#question').value)};window.addEventListener('beforeunload',stopSpeech);boot().catch(e=>{console.error(e);$('#status').textContent='Ошибка загрузки';$('#pageText').textContent='Не удалось открыть книгу: '+e.message});