let book=null,current=1,utterance=null;const $=s=>document.querySelector(s);const stopWords=new Set('и в во на не что он она это как к с со из за по от для а но же мы вы они я его ее их у о об до при бы был была были быть или который которая которые где когда уже еще'.split(' '));
const norm=s=>(s||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9 ]+/g,' ').replace(/\s+/g,' ').trim();const words=s=>norm(s).split(' ').filter(x=>x.length>2&&!stopWords.has(x));
function showPage(n){current=Math.max(1,Math.min(book.pages.length,Number(n)||1));$('#pageInput').value=current;$('#pageText').textContent=book.pages[current-1].text||'На этой странице текст не извлечён.';$('#prev').disabled=current<=1;$('#next').disabled=current>=book.pages.length;stopSpeech()}
function stopSpeech(){speechSynthesis.cancel();utterance=null;$('#stop').disabled=true;$('#speak').disabled=false}
function speak(){stopSpeech();const t=book.pages[current-1].text;if(!t)return;utterance=new SpeechSynthesisUtterance(t);utterance.lang='ru-RU';utterance.rate=Number($('#rate').value);utterance.onend=stopSpeech;utterance.onerror=stopSpeech;speechSynthesis.speak(utterance);$('#stop').disabled=false;$('#speak').disabled=true}
function scorePage(p,qw){const t=norm(p.text);let score=0;for(const w of qw){const c=t.split(w).length-1;score+=Math.min(c,6)*(w.length>6?3:2);if(t.includes(w))score+=2}return score}
function snippet(text,qw){let pos=-1;for(const w of qw){const p=norm(text).indexOf(w);if(p>=0){pos=p;break}}if(pos<0)return text.slice(0,420);const raw=text;const start=Math.max(0,pos-120),end=Math.min(raw.length,start+520);return(start?'…':'')+raw.slice(start,end)+(end<raw.length?'…':'')}
function ask(q){const qw=[...new Set(words(q))];if(!qw.length)return[];return book.pages.map(p=>({...p,score:scorePage(p,qw)})).filter(p=>p.score>0).sort((a,b)=>b.score-a.score).slice(0,4).map(p=>({...p,snippet:snippet(p.text,qw)}))}
function renderAnswer(q){const hits=ask(q),box=$('#answer');if(!hits.length){box.innerHTML='<b>В тексте книги не найдено достаточно совпадений.</b><p>Попробуйте сформулировать вопрос другими словами.</p>';return}const lead=hits.slice(0,2).map(x=>x.snippet).join(' ');box.innerHTML=`<b>По тексту книги наиболее релевантны страницы ${hits.map(x=>x.page).join(', ')}.</b><p>${lead}</p><p><small>Это тестовый поисковый ответ без генеративной модели. Следующий этап — RAG, который будет формулировать связный ответ только по найденным фрагментам.</small></p>`+hits.map(x=>`<button class="source" data-page="${x.page}">стр. ${x.page} — ${x.snippet.slice(0,180)}</button>`).join('');box.querySelectorAll('.source').forEach(b=>b.onclick=()=>{showPage(b.dataset.page);document.querySelector('[data-tab="read"]').click()})}
async function boot(){book=await fetch('data/gagarin-pages.json').then(r=>r.json());$('#driveViewer').src=book.drivePreview;showPage(1)}
$('#prev').onclick=()=>showPage(current-1);$('#next').onclick=()=>showPage(current+1);$('#pageInput').onchange=e=>showPage(e.target.value);$('#speak').onclick=speak;$('#stop').onclick=stopSpeech;$('#rate').onchange=()=>{if(utterance)speak()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#askForm').onsubmit=e=>{e.preventDefault();renderAnswer($('#question').value)};window.addEventListener('beforeunload',stopSpeech);boot();
